#spring.application.name=backend
#
## --- PostgreSQL ---
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=validate
#
## Liquibase
#spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
#
## Railway dynamic port
#server.port=${PORT:8080}
spring.application.name=backend

# --- PostgreSQL (Railway) ---
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.ddl-auto=update

# --- Schema (IMPORTANT) ---
spring.jpa.properties.hibernate.default_schema=public
spring.liquibase.default-schema=public

# --- Liquibase ---
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
#spring.liquibase.enabled=true

# --- Railway dynamic port ---
server.port=${PORT:8080}
